// FILE: PrivacyPage.jsx
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
	ShieldCheck, Lock, Users, FileText, ScrollText, AlertCircle, 
	Server, Ban, X, Globe, Download, CreditCard, 
	ChevronDown, Activity, Clock, Eye, Mail, Key, Zap, CheckCircle2 
} from 'lucide-react';

const PrivacyPage = ({ onAccept, isFooterView = false, onClose, initialTab = 'privacy' }) => {
	const [activeTab, setActiveTab] = useState(initialTab);	
	const [canAccept, setCanAccept] = useState(false);
	
	const handleScroll = (e) => {
		if (isFooterView) return;
		const bottom = e.target.scrollHeight - e.target.scrollTop <= e.target.clientHeight + 50;
		if (bottom) setCanAccept(true);
	};

    // ... (generateDownload function remains the same)
	const generateDownload = (filename, title, content) => {
		const fullText = `${title}\n\nGenerated by Auditor Veritas System\nDate: ${new Date().toLocaleDateString()}\n\n${content}`;
		const element = document.createElement("a");
		const file = new Blob([fullText], {type: 'text/plain'}); 
		element.href = URL.createObjectURL(file);
		element.download = filename;
		document.body.appendChild(element);
		element.click();
		document.body.removeChild(element);
	};

	return (
		<div className="fixed inset-0 z-[9999] bg-gray-900/95 backdrop-blur-xl flex items-center justify-center sm:p-4 animate-fade-in">
			<motion.div	
				initial={{ scale: 0.95, opacity: 0 }}	
				animate={{ scale: 1, opacity: 1 }}
				exit={{ scale: 0.95, opacity: 0 }}
				className="w-full sm:max-w-4xl bg-[#020617] sm:rounded-3xl rounded-none shadow-2xl border border-white/10 overflow-hidden flex flex-col h-full sm:h-[85vh] relative"
			>
                {/* Header Section */}
				<button onClick={onClose} className="absolute top-6 right-6 z-50 p-2 bg-white/5 hover:bg-white/10 rounded-full text-slate-400 hover:text-white transition-colors border border-white/5">
					<X size={20} />
				</button>

				<div className="p-8 pb-0 text-center shrink-0 relative z-10">
					<div className="flex p-1 bg-white/5 rounded-xl mb-8 relative border border-white/10 backdrop-blur-xl max-w-md mx-auto">
						<button onClick={() => setActiveTab('privacy')} className={`flex-1 py-3 text-xs sm:text-sm font-bold rounded-lg transition-all relative z-10 flex items-center justify-center gap-2 ${activeTab === 'privacy' ? 'text-white' : 'text-slate-400 hover:text-slate-200'}`}>
							<Lock size={14} /> Privacy & GDPR
						</button>
						<button onClick={() => setActiveTab('terms')} className={`flex-1 py-3 text-xs sm:text-sm font-bold rounded-lg transition-all relative z-10 flex items-center justify-center gap-2 ${activeTab === 'terms' ? 'text-white' : 'text-slate-400 hover:text-slate-200'}`}>
							<ScrollText size={14} /> Terms of Service
						</button>
						<motion.div	
							className="absolute top-1 bottom-1 bg-blue-600 rounded-lg shadow-lg shadow-blue-500/20"
							initial={false}
							animate={{ left: activeTab === 'privacy' ? '4px' : '50%', width: 'calc(50% - 4px)' }}
							transition={{ type: "spring", stiffness: 300, damping: 30 }}
						/>
					</div>
				</div>

				<div className="flex-1 overflow-y-auto custom-scrollbar p-8 space-y-8 relative z-10 scroll-smooth bg-slate-900/50" onScroll={handleScroll}>
					<AnimatePresence mode='wait'>
						{activeTab === 'privacy' ? (
							<motion.div key="privacy" initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 10 }} className="space-y-6 pb-8">
								<p className="text-xs uppercase tracking-wider font-bold text-emerald-500">Updated: December 2, 2025</p>
								
								<Section title="1. Data Sovereignty & EU Location" icon={Globe} color="blue">
									<p className="text-sm mb-3 text-slate-300">
										Auditor Veritas infrastructure is strictly <strong>EU-Sovereign</strong>. No customer data leaves the European Economic Area (EEA).
									</p>
								</Section>

								<Section title="2. Sub-processors (Strictly Minimal)" icon={Users} color="slate">
									<p className="text-sm mb-3 text-slate-300">
										We have eliminated US-based sub-processors (e.g., Stripe, transactional email providers) to minimize data exposure.
									</p>
									<div className="mt-3 overflow-hidden rounded-lg border border-white/10">
										<table className="w-full text-xs text-left text-slate-300">
											<thead className="bg-white/5 text-slate-400">
												<tr><th className="p-3">Entity</th><th className="p-3">Role</th><th className="p-3">Location</th></tr>
											</thead>
											<tbody className="divide-y divide-white/5">
												<tr><td className="p-3 font-bold">Supabase</td><td className="p-3">Database (AWS Wrapper)</td><td className="p-3">EU (Frankfurt)</td></tr>
												<tr><td className="p-3 font-bold">Render</td><td className="p-3">Application Hosting</td><td className="p-3">EU (Frankfurt)</td></tr>
											</tbody>
										</table>
									</div>
								</Section>

                                {/* ... Other Sections (Retention, Breach, Rights) remain similar ... */}
                                <Section title="3. Communication Privacy" icon={Mail} color="emerald">
                                    <p className="text-sm text-slate-300">
                                        To protect your metadata, Auditor Veritas does <strong>not</strong> use third-party email automation for system alerts. 
                                        Team invitations and API keys are generated cryptographically and must be shared via your own secure channels (Signal, Matrix, Corporate Email).
                                    </p>
                                </Section>

							</motion.div>
						) : (
							<motion.div key="terms" initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -10 }} className="space-y-6 pb-8">
                                {/* ... Terms Sections ... */}
								<Section title="Invoicing & Enterprise Access" icon={CreditCard} color="emerald">
									<p className="text-sm mb-3 text-slate-300">
										Auditor Veritas operates on a Master Services Agreement (MSA) basis. We do not process automatic card payments. Access is granted upon signed invoice.
									</p>
								</Section>
                                {/* ... Liability/Law Sections remain ... */}
							</motion.div>
						)}
					</AnimatePresence>
				</div>

				{/* FOOTER ACTION BAR */}
				{!isFooterView && (
					<div className="p-6 border-t border-white/10 bg-[#020617] shrink-0 z-20 relative">
						{!canAccept && (
							<div className="absolute -top-12 left-0 w-full flex justify-center pointer-events-none">
								<motion.div initial={{ y: 0 }} animate={{ y: 5 }} transition={{ repeat: Infinity, repeatType: "reverse", duration: 1 }} className="bg-blue-600 text-white text-[10px] font-bold px-4 py-1.5 rounded-full flex items-center shadow-lg gap-2">
									Scroll to read <ChevronDown size={12}/>
								</motion.div>
							</div>
						)}
						<div className="flex gap-4">
							<button onClick={onClose} className="flex-1 py-4 rounded-xl font-bold text-base transition-colors bg-white/5 text-slate-400 hover:bg-white/10 hover:text-white border border-white/5">
								Decline
							</button>
							<button onClick={onAccept} disabled={!canAccept} className={`flex-1 py-4 rounded-xl font-bold text-base transition-all duration-300 flex items-center justify-center gap-2 shadow-lg ${canAccept ? 'bg-blue-600 text-white hover:bg-blue-500' : 'bg-slate-800 text-slate-500 cursor-not-allowed border border-white/5'}`}>
								{canAccept ? <><ShieldCheck size={20} /> Accept & Continue</> : 'Read to Accept'}
							</button>
						</div>
					</div>
				)}
			</motion.div>
		</div>
	);
};

// Sub-components (Section, FeatureBox) remain as defined in your original file...
const Section = ({ title, icon: Icon, color, children }) => (
	<div className="bg-white/5 p-6 rounded-2xl border border-white/5 hover:border-white/10 transition-colors">
		<div className="flex items-center mb-4 pb-3 border-b border-white/5">
			<div className={`p-2 rounded-lg bg-${color}-500/10 mr-3`}><Icon className={`w-5 h-5 text-${color}-400`} /></div>
			<h3 className="font-bold text-white text-lg">{title}</h3>
		</div>
		{children}
	</div>
);

export default PrivacyPage;