import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
	ShieldCheck, Lock, Users, FileText, ScrollText, AlertCircle, 
	Server, Ban, X, Globe, Download, CreditCard, 
	ChevronDown, Activity, Clock, Eye, Mail, Key, Zap, CheckCircle2 
} from 'lucide-react';
// Jag antar att denna import fungerar i ditt projekt
import { DarkAuroraBackground } from './SharedBackgrounds'; 

const PrivacyPage = ({ onAccept, isFooterView = false, onClose, initialTab = 'privacy' }) => {
	const [activeTab, setActiveTab] = useState(initialTab);	
	const [canAccept, setCanAccept] = useState(false);
	
	const handleScroll = (e) => {
		if (isFooterView) return;
		const bottom = e.target.scrollHeight - e.target.scrollTop <= e.target.clientHeight + 50;
		if (bottom) setCanAccept(true);
	};

	const generateDownload = (filename, title, content) => {
		const fullText = `${title}\n\nGenerated by Auditor Veritas System\nDate: ${new Date().toLocaleDateString()}\n\n${content}`;
		const element = document.createElement("a");
		const file = new Blob([fullText], {type: 'text/plain'}); 
		element.href = URL.createObjectURL(file);
		element.download = filename;
		document.body.appendChild(element);
		element.click();
		document.body.removeChild(element);
	};

	return (
		<div className="fixed inset-0 z-[9999] bg-gray-900/80 backdrop-blur-xl flex items-center justify-center sm:p-4 animate-fade-in">
			<motion.div	
				initial={{ scale: 0.95, opacity: 0 }}	
				animate={{ scale: 1, opacity: 1 }}
				exit={{ scale: 0.95, opacity: 0 }}
				transition={{ type: "spring", damping: 25, stiffness: 300 }}
				className="w-full sm:max-w-4xl bg-slate-900 sm:rounded-3xl rounded-none shadow-2xl border border-white/10 overflow-hidden flex flex-col h-full sm:h-[85vh] relative"
			>
				{/* Background & Close Button */}
				<div className="absolute inset-0 pointer-events-none">
					<div className="absolute inset-0 bg-gradient-to-b from-slate-900 to-[#020617]" /> 
					<div className="absolute top-0 left-0 w-full h-full opacity-20 bg-[url('https://grainy-gradients.vercel.app/noise.svg')]" />
				</div>

				<button onClick={onClose} className="absolute top-6 right-6 z-50 p-2 bg-white/5 hover:bg-white/10 rounded-full text-slate-400 hover:text-white transition-colors border border-white/5">
					<X size={20} />
				</button>

				<div className="p-8 pb-0 text-center shrink-0 relative z-10">
					<div className="flex p-1 bg-black/40 rounded-xl mb-8 relative border border-white/10 backdrop-blur-xl max-w-md mx-auto">
						<button onClick={() => setActiveTab('privacy')} className={`flex-1 py-3 text-xs sm:text-sm font-bold rounded-lg transition-all relative z-10 flex items-center justify-center gap-2 ${activeTab === 'privacy' ? 'text-white' : 'text-slate-400 hover:text-slate-200'}`}>
							<Lock size={14} /> Privacy & GDPR
						</button>
						<button onClick={() => setActiveTab('terms')} className={`flex-1 py-3 text-xs sm:text-sm font-bold rounded-lg transition-all relative z-10 flex items-center justify-center gap-2 ${activeTab === 'terms' ? 'text-white' : 'text-slate-400 hover:text-slate-200'}`}>
							<ScrollText size={14} /> Terms of Service
						</button>
						<motion.div	
							className="absolute top-1 bottom-1 bg-blue-600 rounded-lg shadow-lg shadow-blue-500/20"
							initial={false}
							animate={{ left: activeTab === 'privacy' ? '4px' : '50%', width: 'calc(50% - 4px)' }}
							transition={{ type: "spring", stiffness: 300, damping: 30 }}
						/>
					</div>
				</div>

				<div className="flex-1 overflow-y-auto custom-scrollbar p-8 space-y-8 relative z-10 scroll-smooth bg-slate-900/50" onScroll={handleScroll}>
					<AnimatePresence mode='wait'>
						{activeTab === 'privacy' ? (
							<motion.div key="privacy" initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 10 }} className="space-y-6 pb-8">
								<p className="text-xs uppercase tracking-wider font-bold text-emerald-500">Effective Date: November 24, 2025</p>
								
								<Section title="1. Data Processor Agreement (DPA)" icon={FileText} color="blue">
									<p className="text-sm mb-3 text-slate-300">
										By using Auditor Veritas, you designate us as a <strong>Data Processor</strong> under GDPR Article 28. We process data solely on your documented instructions.
									</p>
									<button 
										onClick={() => generateDownload("AuditorVeritas_DPA_Signed.txt", "DATA PROCESSOR AGREEMENT", "AGREEMENT BETWEEN: Auditor Veritas AB AND Customer...\n\n1. DEFINITIONS...\n2. PROCESSING...")}
										className="inline-flex items-center gap-2 text-xs font-bold text-blue-300 bg-blue-500/10 px-4 py-2 rounded-lg hover:bg-blue-500/20 transition-colors border border-blue-500/30 w-full sm:w-auto justify-center"
									>
										<Download size={14}/> Download Standard DPA (PDF)
									</button>
								</Section>

								<Section title="2. Security Architecture" icon={Server} color="indigo">
									<div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-2">
										<FeatureBox title="Storage Location" desc="EU (Frankfurt / Ireland)" verified />
										<FeatureBox title="Encryption at Rest" desc="AES-256-GCM" verified />
										<FeatureBox title="Transport Security" desc="TLS 1.3 Only" verified />
										<FeatureBox title="Key Management" desc="HSM Rotated & Isolated" verified />
									</div>
								</Section>

								<Section title="3. Data Retention & Deletion" icon={Clock} color="orange">
									<p className="text-sm mb-2 text-slate-300">
										We retain audit logs for the duration of your subscription term plus 30 days, unless configured otherwise via the Dashboard retention settings.
									</p>
									<ul className="list-disc pl-5 space-y-1 text-sm marker:text-orange-500 text-slate-400">
										<li><strong>Deletion:</strong> Upon account termination, crypto-shredding is performed within 72 hours.</li>
										<li><strong>Backups:</strong> Encrypted backups are retained for 30 days for disaster recovery.</li>
									</ul>
								</Section>

								<Section title="4. Sub-processors" icon={Users} color="slate">
									<p className="text-sm mb-3 text-slate-300">
										We only use sub-processors located in the EU or those covered by Standard Contractual Clauses (SCCs) for cross-border data transfer.
									</p>
									<div className="mt-3 overflow-hidden rounded-lg border border-white/10">
										<table className="w-full text-xs text-left text-slate-300">
											<thead className="bg-white/5 text-slate-400">
												<tr><th className="p-3">Entity</th><th className="p-3">Role</th><th className="p-3">Location</th></tr>
											</thead>
											<tbody className="divide-y divide-white/5">
												<tr><td className="p-3 font-bold">Supabase</td><td className="p-3">Database Provider</td><td className="p-3">EU (Ireland)</td></tr>
												<tr><td className="p-3 font-bold">Render</td><td className="p-3">Application Hosting</td><td className="p-3">EU (Germany)</td></tr>
												<tr><td className="p-3 font-bold">Stripe</td><td className="p-3">Payment Processing</td><td className="p-3">US (SCCs)</td></tr>
												<tr><td className="p-3 font-bold">Resend</td><td className="p-3">Transactional Email</td><td className="p-3">US (SCCs)</td></tr>
											</tbody>
										</table>
									</div>
								</Section>
								
								<Section title="5. Data Breach Notification" icon={Mail} color="red">
									<p className="text-sm mb-2 text-slate-300">
										In the event of a Personal Data Breach, Auditor Veritas will notify you without undue delay, and in any case, within 72 hours of becoming aware of it.
									</p>
									<ul className="list-disc pl-5 space-y-1 text-sm marker:text-red-500 text-slate-400">
										<li>Notification will be via email to your registered contact address.</li>
										<li>The notification will include details of the nature of the breach, likely consequences, and measures taken.</li>
									</ul>
								</Section>
								
								<Section title="6. Data Subject Rights Fulfillment" icon={Eye} color="purple">
									<p className="text-sm mb-3 text-slate-300">
										As the Data Processor, we assist you (the Controller) in fulfilling data subject requests under GDPR Articles 12-22.
									</p>
									<ul className="list-disc pl-5 space-y-1 text-sm marker:text-purple-500 text-slate-400">
										<li><strong>Access (Art 15):</strong> We provide tools to export logs for the data subject.</li>
										<li><strong>Rectification (Art 16):</strong> Changes are handled by logging a cryptographic "amendment" event, preserving the original immutable record.</li>
										<li><strong>Erasure (Art 17):</strong> Executed via Crypto-Shredding (immediate key destruction).</li>
										<li><strong>Portability (Art 20):</strong> We provide the necessary format (JSON/CSV) for data portability.</li>
									</ul>
								</Section>

								<div className="p-4 rounded-xl border border-white/10 bg-slate-800/50 text-xs text-slate-400">
									<strong>Contact DPO:</strong> For privacy concerns, contact our Data Protection Officer at <a href="mailto:privacy@auditorveritas.com" className="text-blue-400 hover:underline">privacy@auditorveritas.com</a>
								</div>
							</motion.div>
						) : (
							<motion.div key="terms" initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -10 }} className="space-y-6 pb-8">
								<div className="flex justify-end mb-6">
									<button 
										onClick={() => generateDownload("AuditorVeritas_Terms_Service.txt", "TERMS OF SERVICE", "1. ACCEPTANCE OF TERMS...")}
										className="text-xs font-bold text-slate-400 hover:text-white flex items-center gap-1"
									>
										<Download size={12}/> Download Terms
									</button>
								</div>

								<Section title="1. Acceptable Use Policy" icon={AlertCircle} color="orange">
									<p className="text-sm mb-3 text-slate-300">You agree to use the API lawfully. You strictly agree <strong>NOT</strong> to:</p>
									<ul className="space-y-2 bg-orange-500/10 p-4 rounded-xl border border-orange-500/20 text-sm text-orange-200">
										<li className="flex gap-2"><Ban size={16} className="shrink-0"/> Reverse engineer the cryptographic proof engine.</li>
										<li className="flex gap-2"><Ban size={16} className="shrink-0"/> Store illegal content, malware, or PII without encryption.</li>
										<li className="flex gap-2"><Ban size={16} className="shrink-0"/> Circumvent rate limits or authentication mechanisms.</li>
									</ul>
								</Section>

								<Section title="2. Service Level Agreement (SLA)" icon={Activity} color="blue">
									<p className="text-sm mb-3 text-slate-300">Enterprise plans guarantee <strong>99.9% Uptime</strong>.</p>
									<ul className="list-disc pl-5 space-y-1 text-sm marker:text-blue-500 text-slate-400">
										<li><strong>Maintenance:</strong> Communicated 48h in advance.</li>
										<li><strong>Incident Response:</strong> Critical issues acknowledged within 1 hour.</li>
										<li><strong>Compensation:</strong> 10% credit per 1% downtime below SLA.</li>
									</ul>
								</Section>
								
								<Section title="3. Data Breach Handling & Reporting" icon={Mail} color="red">
									<p className="text-sm mb-3 text-slate-300">
										We will notify you (the Controller) without undue delay upon becoming aware of a confirmed Personal Data Breach.
									</p>
									<ul className="list-disc pl-5 space-y-1 text-sm marker:text-red-500 text-slate-400">
										<li><strong>Timeframe:</strong> Notification within 72 hours (GDPR Article 33/34 compliance).</li>
										<li><strong>Content:</strong> Includes the nature of the breach, estimated scope, and measures taken.</li>
									</ul>
								</Section>

								<Section title="4. Fees and Payments" icon={CreditCard} color="emerald">
									<p className="text-sm mb-3 text-slate-300">
										Subscription fees are billed in advance via Stripe.
									</p>
									<ul className="list-disc pl-5 space-y-1 text-sm marker:text-emerald-500 text-slate-400">
										<li><strong>Non-refundable:</strong> Fees paid are non-refundable except as required by law.</li>
										<li><strong>Taxes:</strong> All fees are exclusive of VAT/Sales Tax.</li>
									</ul>
								</Section>

								<Section title="5. Limitation of Liability" icon={ShieldCheck} color="slate">
									<p className="text-sm text-slate-400 text-justify leading-relaxed">
										TO THE MAXIMUM EXTENT PERMITTED BY LAW, AUDITOR VERITAS SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES. OUR AGGREGATE LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
									</p>
								</Section>
								
								<Section title="6. Governing Law & Jurisdiction" icon={Globe} color="cyan">
									<p className="text-sm text-slate-400 text-justify leading-relaxed">
										These Terms shall be governed by and construed in accordance with the laws of **Sweden**. The parties agree that the courts of **Gothenburg, Sweden** shall have exclusive jurisdiction over any disputes arising out of these Terms.
									</p>
								</Section>
							</motion.div>
						)}
					</AnimatePresence>
				</div>

				{/* FOOTER ACTION BAR */}
				{!isFooterView && (
					<div className="p-6 border-t border-white/10 bg-slate-900 shrink-0 z-20 relative">
						{/* NYTT: VARNINGSRUTA FÖR ATT HÖJA PROFESSIONALISMEN */}
						<div className="flex items-center gap-2 mb-4 p-3 bg-red-800/20 rounded-lg border border-red-500/30 text-red-300">
							<AlertCircle size={18} className="shrink-0" />
							<p className="text-xs font-medium">WARNING: Accepting these terms is a legal and security commitment. Do not proceed unless fully reviewed.</p>
						</div>


						{!canAccept && (
							<div className="absolute -top-12 left-0 w-full flex justify-center pointer-events-none">
								<motion.div initial={{ y: 0 }} animate={{ y: 5 }} transition={{ repeat: Infinity, repeatType: "reverse", duration: 1 }} className="bg-blue-600 text-white text-[10px] font-bold px-4 py-1.5 rounded-full flex items-center shadow-lg gap-2">
									Please read to the end <ChevronDown size={12}/>
								</motion.div>
							</div>
						)}
						<div className="flex gap-4">
							{/* FIX: Avvisar avtalet och stänger */}
							<button onClick={onClose} className="flex-1 py-4 rounded-xl font-bold text-base transition-colors bg-slate-800 text-slate-400 hover:bg-slate-700 hover:text-white border border-white/5">
								Decline (Reject Contract)
							</button>
							
							<button onClick={onAccept} disabled={!canAccept} className={`flex-1 py-4 rounded-xl font-bold text-base transition-all duration-300 flex items-center justify-center gap-2 shadow-lg ${canAccept ? 'bg-blue-600 text-white hover:bg-blue-500 hover:shadow-blue-500/25' : 'bg-slate-800 text-slate-500 cursor-not-allowed border border-white/5'}`}>
								{canAccept ? <><ShieldCheck size={20} /> I Accept Terms & Privacy Policy</> : 'Scroll to Accept'}
							</button>
						</div>
					</div>
				)}
			</motion.div>
		</div>
	);
};

// --- SUB-KOMPONENTER ---

const Section = ({ title, icon: Icon, color, children }) => (
	<div className="bg-white/5 p-6 rounded-2xl border border-white/5 hover:border-white/10 transition-colors">
		<div className="flex items-center mb-4 pb-3 border-b border-white/5">
			<div className={`p-2 rounded-lg bg-${color}-500/10 mr-3`}><Icon className={`w-5 h-5 text-${color}-400`} /></div>
			<h3 className="font-bold text-white text-lg">{title}</h3>
		</div>
		{children}
	</div>
);

const FeatureBox = ({ title, desc, verified }) => (
	<div className="bg-black/20 p-3 rounded-lg border border-white/5 flex justify-between items-center">
		<div><p className="font-bold text-slate-300 text-xs">{title}</p><p className="text-[11px] text-slate-500">{desc}</p></div>
		{verified && <div className="text-emerald-400"><CheckCircleMini /></div>}
	</div>
);

const CheckCircleMini = () => (<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>);

export default PrivacyPage;